package com.astro.storm.localization

/**
 * String resources for all supported languages
 * Production-grade Nepali translations for Vedic astrology terminology
 */
object Strings {

    private val englishStrings: Map<StringKey, String> = mapOf(
        // Common / General
        StringKey.APP_NAME to "AstroStorm",
        StringKey.OK to "OK",
        StringKey.CANCEL to "Cancel",
        StringKey.SAVE to "Save",
        StringKey.DELETE to "Delete",
        StringKey.EDIT to "Edit",
        StringKey.BACK to "Back",
        StringKey.NEXT to "Next",
        StringKey.CLOSE to "Close",
        StringKey.RETRY to "Retry",
        StringKey.LOADING to "Loading...",
        StringKey.ERROR to "Error",
        StringKey.SUCCESS to "Success",
        StringKey.WARNING to "Warning",
        StringKey.INFO to "Information",
        StringKey.YES to "Yes",
        StringKey.NO to "No",
        StringKey.CONFIRM to "Confirm",
        StringKey.SELECT to "Select",
        StringKey.SEARCH to "Search",
        StringKey.SHARE to "Share",
        StringKey.COPY to "Copy",
        StringKey.COPIED to "Copied",
        StringKey.UNKNOWN to "Unknown",
        StringKey.NOT_AVAILABLE to "Not available",

        // Error Messages
        StringKey.ERROR_GENERIC to "Something went wrong. Please try again.",
        StringKey.ERROR_NETWORK to "Network error. Please check your connection.",
        StringKey.ERROR_INVALID_INPUT to "Invalid input. Please check your entries.",
        StringKey.ERROR_CALCULATION_FAILED to "Calculation failed. Please try again.",
        StringKey.ERROR_NO_DATA to "No data available.",
        StringKey.ERROR_PERMISSION_DENIED to "Permission denied.",

        // Navigation / Tabs
        StringKey.TAB_HOME to "Home",
        StringKey.TAB_INSIGHTS to "Insights",
        StringKey.TAB_SETTINGS to "Settings",
        StringKey.NAV_BIRTH_CHART to "Birth Chart",
        StringKey.NAV_DASHAS to "Dashas",
        StringKey.NAV_YOGAS to "Yogas",
        StringKey.NAV_PLANETS to "Planets",
        StringKey.NAV_TRANSITS to "Transits",
        StringKey.NAV_MATCHMAKING to "Matchmaking",
        StringKey.NAV_PANCHANGA to "Panchanga",
        StringKey.NAV_MUHURTA to "Muhurta",
        StringKey.NAV_PRASHNA to "Prashna",
        StringKey.NAV_REMEDIES to "Remedies",
        StringKey.NAV_ASHTAKAVARGA to "Ashtakavarga",
        StringKey.NAV_VARSHAPHALA to "Varshaphala",

        // Settings Screen
        StringKey.SETTINGS_TITLE to "Settings",
        StringKey.SETTINGS_LANGUAGE to "Language",
        StringKey.SETTINGS_LANGUAGE_DESC to "Select your preferred language",
        StringKey.SETTINGS_DATE_FORMAT to "Date Format",
        StringKey.SETTINGS_DATE_FORMAT_DESC to "Choose date display format",
        StringKey.SETTINGS_DATE_SYSTEM to "Date System",
        StringKey.SETTINGS_DATE_SYSTEM_AD to "AD (Gregorian)",
        StringKey.SETTINGS_DATE_SYSTEM_BS to "BS (Bikram Sambat)",
        StringKey.SETTINGS_THEME to "Theme",
        StringKey.SETTINGS_THEME_DESC to "Choose app appearance",
        StringKey.SETTINGS_THEME_DARK to "Dark",
        StringKey.SETTINGS_THEME_LIGHT to "Light",
        StringKey.SETTINGS_THEME_SYSTEM to "System",
        StringKey.SETTINGS_ABOUT to "About",
        StringKey.SETTINGS_VERSION to "Version",
        StringKey.SETTINGS_AYANAMSA to "Ayanamsa",
        StringKey.SETTINGS_AYANAMSA_DESC to "Select astronomical correction",
        StringKey.SETTINGS_HOUSE_SYSTEM to "House System",
        StringKey.SETTINGS_HOUSE_SYSTEM_DESC to "Choose house calculation method",

        // Chart Input Screen
        StringKey.CHART_INPUT_TITLE to "Birth Chart",
        StringKey.CHART_INPUT_NEW to "New Birth Chart",
        StringKey.CHART_INPUT_IDENTITY to "Identity",
        StringKey.CHART_INPUT_NAME to "Full name",
        StringKey.CHART_INPUT_NAME_PLACEHOLDER to "Enter full name",
        StringKey.CHART_INPUT_GENDER to "Gender",
        StringKey.CHART_INPUT_GENDER_MALE to "Male",
        StringKey.CHART_INPUT_GENDER_FEMALE to "Female",
        StringKey.CHART_INPUT_GENDER_OTHER to "Other",
        StringKey.CHART_INPUT_LOCATION to "Location",
        StringKey.CHART_INPUT_LOCATION_PLACEHOLDER to "Search city or enter manually",
        StringKey.CHART_INPUT_DATE_TIME to "Date & Time",
        StringKey.CHART_INPUT_DATE to "Date",
        StringKey.CHART_INPUT_TIME to "Time",
        StringKey.CHART_INPUT_SELECT_DATE to "Select date",
        StringKey.CHART_INPUT_SELECT_TIME to "Select time",
        StringKey.CHART_INPUT_TIMEZONE to "Timezone",
        StringKey.CHART_INPUT_COORDINATES to "Coordinates",
        StringKey.CHART_INPUT_LATITUDE to "Latitude",
        StringKey.CHART_INPUT_LONGITUDE to "Longitude",
        StringKey.CHART_INPUT_ALTITUDE to "Altitude",
        StringKey.CHART_INPUT_ALTITUDE_OPTIONAL to "Altitude (m) - Optional",
        StringKey.CHART_INPUT_GENERATE to "Generate",
        StringKey.CHART_INPUT_GENERATE_SAVE to "Generate & Save",
        StringKey.CHART_INPUT_ERROR_TITLE to "Input Error",
        StringKey.CHART_INPUT_ERROR_LATITUDE_LONGITUDE to "Please enter valid latitude and longitude",
        StringKey.CHART_INPUT_ERROR_LATITUDE_RANGE to "Latitude must be between -90 and 90",
        StringKey.CHART_INPUT_ERROR_LONGITUDE_RANGE to "Longitude must be between -180 and 180",
        StringKey.CHART_INPUT_GO_BACK to "Go back",

        // Profile Edit Screen
        StringKey.PROFILE_EDIT_TITLE to "Edit Profile",
        StringKey.PROFILE_EDIT_NO_DATA to "No chart data available. Please select a profile to edit.",
        StringKey.PROFILE_EDIT_SAVE_SUCCESS to "Profile saved successfully",
        StringKey.PROFILE_EDIT_SAVE_ERROR to "Please check your input values",

        // Birth Chart Screen
        StringKey.BIRTH_CHART_TITLE to "Birth Chart",
        StringKey.BIRTH_CHART_RASHI to "Rashi",
        StringKey.BIRTH_CHART_NAVAMSA to "Navamsa",
        StringKey.BIRTH_CHART_CHALIT to "Chalit",
        StringKey.BIRTH_CHART_DIVISIONAL to "Divisional Charts",
        StringKey.BIRTH_CHART_ASCENDANT to "Ascendant",
        StringKey.BIRTH_CHART_MOON_SIGN to "Moon Sign",
        StringKey.BIRTH_CHART_SUN_SIGN to "Sun Sign",
        StringKey.BIRTH_CHART_NAKSHATRA to "Nakshatra",
        StringKey.BIRTH_CHART_PADA to "Pada",
        StringKey.BIRTH_CHART_DEGREE to "Degree",

        // Planets Screen
        StringKey.PLANETS_TITLE to "Planets",
        StringKey.PLANETS_POSITION to "Position",
        StringKey.PLANETS_HOUSE to "House",
        StringKey.PLANETS_SIGN to "Sign",
        StringKey.PLANETS_DEGREE to "Degree",
        StringKey.PLANETS_NAKSHATRA to "Nakshatra",
        StringKey.PLANETS_PADA to "Pada",
        StringKey.PLANETS_RETROGRADE to "Retrograde",
        StringKey.PLANETS_COMBUSTION to "Combust",
        StringKey.PLANETS_EXALTED to "Exalted",
        StringKey.PLANETS_DEBILITATED to "Debilitated",
        StringKey.PLANETS_OWN_SIGN to "Own Sign",
        StringKey.PLANETS_FRIENDLY to "Friendly",
        StringKey.PLANETS_NEUTRAL to "Neutral",
        StringKey.PLANETS_ENEMY to "Enemy",
        StringKey.PLANETS_DIGNITY to "Dignity",

        // Planet Names
        StringKey.PLANET_SUN to "Sun",
        StringKey.PLANET_MOON to "Moon",
        StringKey.PLANET_MARS to "Mars",
        StringKey.PLANET_MERCURY to "Mercury",
        StringKey.PLANET_JUPITER to "Jupiter",
        StringKey.PLANET_VENUS to "Venus",
        StringKey.PLANET_SATURN to "Saturn",
        StringKey.PLANET_RAHU to "Rahu",
        StringKey.PLANET_KETU to "Ketu",
        StringKey.PLANET_ASCENDANT to "Ascendant",

        // Zodiac Signs
        StringKey.SIGN_ARIES to "Aries",
        StringKey.SIGN_TAURUS to "Taurus",
        StringKey.SIGN_GEMINI to "Gemini",
        StringKey.SIGN_CANCER to "Cancer",
        StringKey.SIGN_LEO to "Leo",
        StringKey.SIGN_VIRGO to "Virgo",
        StringKey.SIGN_LIBRA to "Libra",
        StringKey.SIGN_SCORPIO to "Scorpio",
        StringKey.SIGN_SAGITTARIUS to "Sagittarius",
        StringKey.SIGN_CAPRICORN to "Capricorn",
        StringKey.SIGN_AQUARIUS to "Aquarius",
        StringKey.SIGN_PISCES to "Pisces",

        // Dashas Screen
        StringKey.DASHAS_TITLE to "Dashas",
        StringKey.DASHAS_MAHADASHA to "Mahadasha",
        StringKey.DASHAS_ANTARDASHA to "Antardasha",
        StringKey.DASHAS_PRATYANTARDASHA to "Pratyantardasha",
        StringKey.DASHAS_CURRENT to "Current",
        StringKey.DASHAS_START_DATE to "Start Date",
        StringKey.DASHAS_END_DATE to "End Date",
        StringKey.DASHAS_DURATION to "Duration",
        StringKey.DASHAS_YEARS to "years",
        StringKey.DASHAS_MONTHS to "months",
        StringKey.DASHAS_DAYS to "days",
        StringKey.DASHAS_VIMSHOTTARI to "Vimshottari",
        StringKey.DASHAS_YOGINI to "Yogini",
        StringKey.DASHAS_CHARA to "Chara",

        // Yogas Screen
        StringKey.YOGAS_TITLE to "Yogas",
        StringKey.YOGAS_COUNT_DETECTED to "yogas detected",
        StringKey.YOGAS_STRENGTH to "Strength",
        StringKey.YOGAS_CATEGORY to "Category",
        StringKey.YOGAS_PLANETS_INVOLVED to "Planets Involved",
        StringKey.YOGAS_EFFECTS to "Effects",
        StringKey.YOGAS_ACTIVATION_PERIOD to "Activation Period",
        StringKey.YOGAS_INFO_TITLE to "About Vedic Yogas",
        StringKey.YOGAS_INFO_DESC to "Yogas are special planetary combinations in Vedic astrology that indicate specific life outcomes and characteristics.",
        StringKey.YOGAS_FILTER_ALL to "All",
        StringKey.YOGAS_NO_YOGAS_FOUND to "No yogas found in this category",

        // Yoga Categories
        StringKey.YOGA_CATEGORY_RAJA to "Raja Yoga",
        StringKey.YOGA_CATEGORY_RAJA_DESC to "Power, authority, leadership",
        StringKey.YOGA_CATEGORY_DHANA to "Dhana Yoga",
        StringKey.YOGA_CATEGORY_DHANA_DESC to "Wealth and prosperity",
        StringKey.YOGA_CATEGORY_MAHAPURUSHA to "Mahapurusha Yoga",
        StringKey.YOGA_CATEGORY_MAHAPURUSHA_DESC to "Exceptional personality traits",
        StringKey.YOGA_CATEGORY_NABHASA to "Nabhasa Yoga",
        StringKey.YOGA_CATEGORY_NABHASA_DESC to "Chart patterns and configurations",
        StringKey.YOGA_CATEGORY_CHANDRA to "Chandra Yoga",
        StringKey.YOGA_CATEGORY_CHANDRA_DESC to "Moon-based combinations",
        StringKey.YOGA_CATEGORY_SOLAR to "Solar Yoga",
        StringKey.YOGA_CATEGORY_SOLAR_DESC to "Sun-based combinations",
        StringKey.YOGA_CATEGORY_SPECIAL to "Special Yoga",
        StringKey.YOGA_CATEGORY_SPECIAL_DESC to "Unique beneficial combinations",
        StringKey.YOGA_CATEGORY_NEGATIVE to "Negative Yoga",
        StringKey.YOGA_CATEGORY_NEGATIVE_DESC to "Challenging combinations",

        // Matchmaking Screen
        StringKey.MATCH_TITLE to "Kundli Milan",
        StringKey.MATCH_SUBTITLE to "Ashtakoota Matching",
        StringKey.MATCH_SELECT_PROFILES to "Select Profiles",
        StringKey.MATCH_BRIDE to "Bride",
        StringKey.MATCH_GROOM to "Groom",
        StringKey.MATCH_TAP_TO_SELECT to "Tap to select",
        StringKey.MATCH_SWAP_PROFILES to "Swap profiles",
        StringKey.MATCH_CLEAR_SELECTION to "Clear selection",
        StringKey.MATCH_CREATE_CHARTS_FIRST to "Create birth charts first to use matchmaking",
        StringKey.MATCH_CONNECTED to "Connected",
        StringKey.MATCH_NOT_CONNECTED to "Not connected",
        StringKey.MATCH_ANALYZING_COMPATIBILITY to "Analyzing Cosmic Compatibility",
        StringKey.MATCH_CALCULATING_DOSHAS to "Calculating Ashtakoota & Doshas...",
        StringKey.MATCH_CALCULATION_ERROR to "Calculation Error",
        StringKey.MATCH_COPIED_TO_CLIPBOARD to "Report copied to clipboard",

        // Compatibility Score
        StringKey.MATCH_COMPATIBILITY_SCORE to "Compatibility Score",
        StringKey.MATCH_TOTAL_SCORE to "Total Score",
        StringKey.MATCH_OUT_OF to "out of",
        StringKey.MATCH_PERCENTAGE to "Compatibility",
        StringKey.MATCH_COMPATIBILITY to "Compatibility",
        StringKey.MATCH_EXCELLENT to "Excellent",
        StringKey.MATCH_GOOD to "Good",
        StringKey.MATCH_AVERAGE to "Average",
        StringKey.MATCH_BELOW_AVERAGE to "Below Average",
        StringKey.MATCH_POOR to "Poor",

        // Tabs
        StringKey.MATCH_TAB_OVERVIEW to "Overview",
        StringKey.MATCH_TAB_GUNAS to "Gunas",
        StringKey.MATCH_TAB_DOSHAS to "Doshas",
        StringKey.MATCH_TAB_NAKSHATRAS to "Nakshatras",
        StringKey.MATCH_TAB_REMEDIES to "Remedies",

        // Overview
        StringKey.MATCH_GUNA_DISTRIBUTION to "Guna Score Distribution",
        StringKey.MATCH_PROFILE_COMPARISON to "Profile Comparison",
        StringKey.MATCH_KEY_CONSIDERATIONS to "Key Considerations",
        StringKey.MATCH_VS to "vs",
        StringKey.MATCH_MOON_SIGN to "Moon Sign",
        StringKey.MATCH_NAKSHATRA to "Nakshatra",
        StringKey.MATCH_PADA to "Pada",
        StringKey.MATCH_FAVORABLE to "Favorable",
        StringKey.MATCH_NEEDS_ATTENTION to "Needs Attention",

        // Gunas
        StringKey.MATCH_GUNA_VARNA to "Varna",
        StringKey.MATCH_GUNA_VASHYA to "Vashya",
        StringKey.MATCH_GUNA_TARA to "Tara",
        StringKey.MATCH_GUNA_YONI to "Yoni",
        StringKey.MATCH_GUNA_GRAHA_MAITRI to "Graha Maitri",
        StringKey.MATCH_GUNA_GANA to "Gana",
        StringKey.MATCH_GUNA_BHAKOOT to "Bhakoot",
        StringKey.MATCH_GUNA_NADI to "Nadi",

        // Doshas
        StringKey.MATCH_MANGLIK to "Manglik",
        StringKey.MATCH_MANGLIK_DOSHA_ANALYSIS to "Manglik Dosha Analysis",
        StringKey.MATCH_MARS_PLACEMENT to "Mars placement compatibility",
        StringKey.MATCH_MARS_IN_HOUSE to "Mars in House",
        StringKey.MATCH_CONTRIBUTING_FACTORS to "Contributing Factors",
        StringKey.MATCH_CANCELLATION_FACTORS to "Cancellation Factors",
        StringKey.MATCH_NADI to "Nadi",
        StringKey.MATCH_NADI_DOSHA to "Nadi Dosha",
        StringKey.MATCH_HEALTH_PROGENY to "Health & Progeny Compatibility",
        StringKey.MATCH_NADI_WARNING to "Same Nadi indicates potential health compatibility concerns. Exceptions may apply based on Nakshatra positions.",
        StringKey.MATCH_BHAKOOT to "Bhakoot",
        StringKey.MATCH_BHAKOOT_DOSHA to "Bhakoot Dosha",
        StringKey.MATCH_FINANCIAL_HARMONY to "Financial & Family Harmony",
        StringKey.MATCH_BRIDE_RASHI to "Bride's Rashi",
        StringKey.MATCH_GROOM_RASHI to "Groom's Rashi",
        StringKey.MATCH_DOSHA_PRESENT to "Dosha Present",
        StringKey.MATCH_PRESENT to "Present",
        StringKey.MATCH_ABSENT to "Absent",
        StringKey.MATCH_NONE to "None",

        // Nakshatra Section
        StringKey.MATCH_NAKSHATRA_COMPATIBILITY to "Nakshatra Compatibility",
        StringKey.MATCH_BIRTH_STAR to "Birth star analysis",
        StringKey.MATCH_BIRTH_NAKSHATRA to "Birth Nakshatra",
        StringKey.MATCH_NAKSHATRA_LORD to "Nakshatra Lord",
        StringKey.MATCH_GANA to "Gana (Nature)",
        StringKey.MATCH_YONI to "Yoni (Animal)",
        StringKey.MATCH_RAJJU_MATCHING to "Rajju Matching",
        StringKey.MATCH_LONGEVITY to "Longevity & Well-being",
        StringKey.MATCH_CONFLICT to "Conflict",
        StringKey.MATCH_COMPATIBLE to "Compatible",
        StringKey.MATCH_RAJJU_DESCRIPTION to "Rajju indicates the cosmic bond that ensures longevity of spouse and harmonious married life. No conflict is highly favorable.",
        StringKey.MATCH_VEDHA_ANALYSIS to "Vedha Analysis",
        StringKey.MATCH_OBSTRUCTION_CHECK to "Obstruction Check",
        StringKey.MATCH_VEDHA_DESCRIPTION to "Vedha represents Nakshatra pairs that create obstacles when combined. Absence of Vedha is considered auspicious for marital harmony.",
        StringKey.MATCH_STREE_DEERGHA to "Stree Deergha & Mahendra",
        StringKey.MATCH_PROSPERITY_FACTORS to "Prosperity & Longevity factors",
        StringKey.MATCH_STREE_DEERGHA_LABEL to "Stree Deergha",
        StringKey.MATCH_MAHENDRA to "Mahendra",
        StringKey.MATCH_BENEFICIAL to "Beneficial",

        // Remedies
        StringKey.MATCH_REMEDIES to "Remedies",
        StringKey.MATCH_SUGGESTED_REMEDIES to "Suggested Remedies",
        StringKey.MATCH_VEDIC_RECOMMENDATIONS to "Traditional Vedic recommendations",
        StringKey.MATCH_REMEDIES_DISCLAIMER to "These remedies are based on traditional Vedic astrology principles. For personalized guidance, consult a qualified astrologer. Compatibility is one of many factors in a successful relationship.",

        // Share Options
        StringKey.MATCH_SHARE_REPORT to "Share Report",
        StringKey.MATCH_COPY_FULL_REPORT to "Copy Full Report",
        StringKey.MATCH_COPY_FULL_DESC to "Copy detailed analysis to clipboard",
        StringKey.MATCH_COPY_SUMMARY to "Copy Summary",
        StringKey.MATCH_COPY_SUMMARY_DESC to "Copy brief compatibility summary",
        StringKey.MATCH_COPY_SCORES to "Copy Scores Only",
        StringKey.MATCH_COPY_SCORES_DESC to "Copy Guna scores breakdown",

        // Empty State
        StringKey.MATCH_NO_CHARTS to "No Charts Available",
        StringKey.MATCH_SELECT_BRIDE_PROFILE to "Select Bride's Profile",
        StringKey.MATCH_SELECT_GROOM_PROFILE to "Select Groom's Profile",
        StringKey.MATCH_PREPARING_ANALYSIS to "Preparing Analysis...",
        StringKey.MATCH_CREATE_CHARTS to "Create birth charts to use matchmaking",
        StringKey.MATCH_SELECT_TAP_CARDS to "Tap on the profile cards above to select",
        StringKey.MATCH_TAP_BRIDE_CARD to "Tap on the bride card to continue",
        StringKey.MATCH_TAP_GROOM_CARD to "Tap on the groom card to continue",
        StringKey.MATCH_CHARTS_AVAILABLE to "charts available",
        StringKey.MATCH_NO_CHARTS_AVAILABLE to "No charts available",
        StringKey.MATCH_SELECTED to "Selected",

        // Panchanga Screen
        StringKey.PANCHANGA_TITLE to "Panchanga",
        StringKey.PANCHANGA_TITHI to "Tithi",
        StringKey.PANCHANGA_VARA to "Vara",
        StringKey.PANCHANGA_NAKSHATRA to "Nakshatra",
        StringKey.PANCHANGA_YOGA to "Yoga",
        StringKey.PANCHANGA_KARANA to "Karana",
        StringKey.PANCHANGA_SUNRISE to "Sunrise",
        StringKey.PANCHANGA_SUNSET to "Sunset",
        StringKey.PANCHANGA_MOONRISE to "Moonrise",
        StringKey.PANCHANGA_MOONSET to "Moonset",
        StringKey.PANCHANGA_RAHUKALA to "Rahu Kala",
        StringKey.PANCHANGA_YAMAGANDA to "Yamaganda",
        StringKey.PANCHANGA_GULIKAKALA to "Gulika Kala",
        StringKey.PANCHANGA_ABHIJIT_MUHURTA to "Abhijit Muhurta",
        StringKey.PANCHANGA_HORA to "Hora",
        StringKey.PANCHANGA_CHOGHADIYA to "Choghadiya",

        // Days of Week
        StringKey.DAY_SUNDAY to "Sunday",
        StringKey.DAY_MONDAY to "Monday",
        StringKey.DAY_TUESDAY to "Tuesday",
        StringKey.DAY_WEDNESDAY to "Wednesday",
        StringKey.DAY_THURSDAY to "Thursday",
        StringKey.DAY_FRIDAY to "Friday",
        StringKey.DAY_SATURDAY to "Saturday",

        // Muhurta Screen
        StringKey.MUHURTA_TITLE to "Muhurta",
        StringKey.MUHURTA_AUSPICIOUS to "Auspicious",
        StringKey.MUHURTA_INAUSPICIOUS to "Inauspicious",
        StringKey.MUHURTA_NEUTRAL to "Neutral",
        StringKey.MUHURTA_MARRIAGE to "Marriage",
        StringKey.MUHURTA_TRAVEL to "Travel",
        StringKey.MUHURTA_EDUCATION to "Education",
        StringKey.MUHURTA_BUSINESS to "Business",
        StringKey.MUHURTA_CONSTRUCTION to "Construction",
        StringKey.MUHURTA_MEDICAL to "Medical",
        StringKey.MUHURTA_LEGAL to "Legal",
        StringKey.MUHURTA_RELIGIOUS to "Religious",
        StringKey.MUHURTA_TODAY to "Today",
        StringKey.MUHURTA_SELECT_DATE to "Select Date",
        StringKey.MUHURTA_BEST_TIMES to "Best Times",
        StringKey.MUHURTA_AVOID_TIMES to "Avoid Times",

        // Prashna Screen
        StringKey.PRASHNA_TITLE to "Prashna",
        StringKey.PRASHNA_ASK_QUESTION to "Ask your question",
        StringKey.PRASHNA_GENERATE_CHART to "Generate Prashna Chart",
        StringKey.PRASHNA_QUESTION_PLACEHOLDER to "Enter your question here...",
        StringKey.PRASHNA_ANALYSIS to "Analysis",
        StringKey.PRASHNA_SIGNIFIER to "Signifier",
        StringKey.PRASHNA_OUTCOME to "Outcome",
        StringKey.PRASHNA_TIMING to "Timing",
        StringKey.PRASHNA_FAVORABLE to "Favorable",
        StringKey.PRASHNA_UNFAVORABLE to "Unfavorable",
        StringKey.PRASHNA_UNCERTAIN to "Uncertain",

        // Remedies Screen
        StringKey.REMEDIES_TITLE to "Remedies",
        StringKey.REMEDIES_GEMSTONES to "Gemstones",
        StringKey.REMEDIES_MANTRAS to "Mantras",
        StringKey.REMEDIES_YANTRAS to "Yantras",
        StringKey.REMEDIES_DONATIONS to "Donations",
        StringKey.REMEDIES_FASTING to "Fasting",
        StringKey.REMEDIES_RITUALS to "Rituals",
        StringKey.REMEDIES_LIFESTYLE to "Lifestyle",
        StringKey.REMEDIES_FAVORABLE_DAY to "Favorable Day",
        StringKey.REMEDIES_METAL to "Metal",
        StringKey.REMEDIES_COLOR to "Color",
        StringKey.REMEDIES_DIRECTION to "Direction",
        StringKey.REMEDIES_DEITY to "Deity",
        StringKey.REMEDIES_RECOMMENDED_FOR to "Recommended For",
        StringKey.REMEDIES_PRECAUTIONS to "Precautions",

        // Transits Screen
        StringKey.TRANSITS_TITLE to "Transits",
        StringKey.TRANSITS_CURRENT to "Current",
        StringKey.TRANSITS_UPCOMING to "Upcoming",
        StringKey.TRANSITS_PAST to "Past",
        StringKey.TRANSITS_PLANET_TRANSIT to "Planet Transit",
        StringKey.TRANSITS_FROM to "From",
        StringKey.TRANSITS_TO to "To",
        StringKey.TRANSITS_DURATION to "Duration",
        StringKey.TRANSITS_EFFECTS to "Effects",
        StringKey.TRANSITS_FAVORABLE to "Favorable",
        StringKey.TRANSITS_CHALLENGING to "Challenging",
        StringKey.TRANSITS_NEUTRAL to "Neutral",

        // Ashtakavarga Screen
        StringKey.ASHTAKAVARGA_TITLE to "Ashtakavarga",
        StringKey.ASHTAKAVARGA_SARVASHTAKA to "Sarvashtakavarga",
        StringKey.ASHTAKAVARGA_POINTS to "Points",
        StringKey.ASHTAKAVARGA_TOTAL to "Total",
        StringKey.ASHTAKAVARGA_STRONG_HOUSES to "Strong Houses",
        StringKey.ASHTAKAVARGA_WEAK_HOUSES to "Weak Houses",
        StringKey.ASHTAKAVARGA_INTERPRETATION to "Interpretation",

        // Varshaphala Screen
        StringKey.VARSHAPHALA_TITLE to "Varshaphala",
        StringKey.VARSHAPHALA_YEAR to "Year",
        StringKey.VARSHAPHALA_MUNTHA to "Muntha",
        StringKey.VARSHAPHALA_SAHAMS to "Sahams",
        StringKey.VARSHAPHALA_YEAR_LORD to "Year Lord",
        StringKey.VARSHAPHALA_PREDICTIONS to "Predictions",
        StringKey.VARSHAPHALA_CAREER to "Career",
        StringKey.VARSHAPHALA_FINANCE to "Finance",
        StringKey.VARSHAPHALA_HEALTH to "Health",
        StringKey.VARSHAPHALA_RELATIONSHIPS to "Relationships",

        // Home Screen
        StringKey.HOME_WELCOME to "Welcome",
        StringKey.HOME_TODAYS_PANCHANGA to "Today's Panchanga",
        StringKey.HOME_CURRENT_DASHA to "Current Dasha",
        StringKey.HOME_QUICK_ACCESS to "Quick Access",
        StringKey.HOME_RECENT_CHARTS to "Recent Charts",
        StringKey.HOME_CREATE_NEW_CHART to "Create New Chart",
        StringKey.HOME_VIEW_ALL_CHARTS to "View All Charts",
        StringKey.HOME_NO_CHARTS to "No charts yet",
        StringKey.HOME_CREATE_FIRST_CHART to "Create your first birth chart",

        // Insights Tab
        StringKey.INSIGHTS_TITLE to "Insights",
        StringKey.INSIGHTS_SUMMARY to "Summary",
        StringKey.INSIGHTS_STRENGTHS to "Strengths",
        StringKey.INSIGHTS_CHALLENGES to "Challenges",
        StringKey.INSIGHTS_OPPORTUNITIES to "Opportunities",
        StringKey.INSIGHTS_CAREER to "Career",
        StringKey.INSIGHTS_RELATIONSHIPS to "Relationships",
        StringKey.INSIGHTS_HEALTH to "Health",
        StringKey.INSIGHTS_FINANCE to "Finance",
        StringKey.INSIGHTS_SPIRITUALITY to "Spirituality",
        StringKey.INSIGHTS_LIFE_PATH to "Life Path",

        // Date Picker
        StringKey.DATE_SELECT_DATE to "Select Date",
        StringKey.DATE_SELECT_TIME to "Select Time",
        StringKey.DATE_AD to "AD",
        StringKey.DATE_BS to "BS",
        StringKey.DATE_TODAY to "Today",
        StringKey.DATE_YEAR to "Year",
        StringKey.DATE_MONTH to "Month",
        StringKey.DATE_DAY to "Day",

        // Nepali Months
        StringKey.MONTH_BAISAKH to "Baisakh",
        StringKey.MONTH_JESTHA to "Jestha",
        StringKey.MONTH_ASHADH to "Ashadh",
        StringKey.MONTH_SHRAWAN to "Shrawan",
        StringKey.MONTH_BHADRA to "Bhadra",
        StringKey.MONTH_ASHWIN to "Ashwin",
        StringKey.MONTH_KARTIK to "Kartik",
        StringKey.MONTH_MANGSIR to "Mangsir",
        StringKey.MONTH_POUSH to "Poush",
        StringKey.MONTH_MAGH to "Magh",
        StringKey.MONTH_FALGUN to "Falgun",
        StringKey.MONTH_CHAITRA to "Chaitra",

        // English Months
        StringKey.MONTH_JANUARY to "January",
        StringKey.MONTH_FEBRUARY to "February",
        StringKey.MONTH_MARCH to "March",
        StringKey.MONTH_APRIL to "April",
        StringKey.MONTH_MAY to "May",
        StringKey.MONTH_JUNE to "June",
        StringKey.MONTH_JULY to "July",
        StringKey.MONTH_AUGUST to "August",
        StringKey.MONTH_SEPTEMBER to "September",
        StringKey.MONTH_OCTOBER to "October",
        StringKey.MONTH_NOVEMBER to "November",
        StringKey.MONTH_DECEMBER to "December",

        // Houses
        StringKey.HOUSE_1 to "1st House",
        StringKey.HOUSE_2 to "2nd House",
        StringKey.HOUSE_3 to "3rd House",
        StringKey.HOUSE_4 to "4th House",
        StringKey.HOUSE_5 to "5th House",
        StringKey.HOUSE_6 to "6th House",
        StringKey.HOUSE_7 to "7th House",
        StringKey.HOUSE_8 to "8th House",
        StringKey.HOUSE_9 to "9th House",
        StringKey.HOUSE_10 to "10th House",
        StringKey.HOUSE_11 to "11th House",
        StringKey.HOUSE_12 to "12th House",

        // House Names
        StringKey.HOUSE_1_NAME to "Lagna (Self)",
        StringKey.HOUSE_2_NAME to "Dhana (Wealth)",
        StringKey.HOUSE_3_NAME to "Sahaja (Siblings)",
        StringKey.HOUSE_4_NAME to "Sukha (Home)",
        StringKey.HOUSE_5_NAME to "Putra (Children)",
        StringKey.HOUSE_6_NAME to "Ripu (Enemies)",
        StringKey.HOUSE_7_NAME to "Kalatra (Spouse)",
        StringKey.HOUSE_8_NAME to "Ayur (Longevity)",
        StringKey.HOUSE_9_NAME to "Dharma (Fortune)",
        StringKey.HOUSE_10_NAME to "Karma (Career)",
        StringKey.HOUSE_11_NAME to "Labha (Gains)",
        StringKey.HOUSE_12_NAME to "Vyaya (Loss)",

        // Nakshatras
        StringKey.NAKSHATRA_ASHWINI to "Ashwini",
        StringKey.NAKSHATRA_BHARANI to "Bharani",
        StringKey.NAKSHATRA_KRITTIKA to "Krittika",
        StringKey.NAKSHATRA_ROHINI to "Rohini",
        StringKey.NAKSHATRA_MRIGASHIRA to "Mrigashira",
        StringKey.NAKSHATRA_ARDRA to "Ardra",
        StringKey.NAKSHATRA_PUNARVASU to "Punarvasu",
        StringKey.NAKSHATRA_PUSHYA to "Pushya",
        StringKey.NAKSHATRA_ASHLESHA to "Ashlesha",
        StringKey.NAKSHATRA_MAGHA to "Magha",
        StringKey.NAKSHATRA_PURVA_PHALGUNI to "Purva Phalguni",
        StringKey.NAKSHATRA_UTTARA_PHALGUNI to "Uttara Phalguni",
        StringKey.NAKSHATRA_HASTA to "Hasta",
        StringKey.NAKSHATRA_CHITRA to "Chitra",
        StringKey.NAKSHATRA_SWATI to "Swati",
        StringKey.NAKSHATRA_VISHAKHA to "Vishakha",
        StringKey.NAKSHATRA_ANURADHA to "Anuradha",
        StringKey.NAKSHATRA_JYESHTHA to "Jyeshtha",
        StringKey.NAKSHATRA_MULA to "Mula",
        StringKey.NAKSHATRA_PURVA_ASHADHA to "Purva Ashadha",
        StringKey.NAKSHATRA_UTTARA_ASHADHA to "Uttara Ashadha",
        StringKey.NAKSHATRA_SHRAVANA to "Shravana",
        StringKey.NAKSHATRA_DHANISHTHA to "Dhanishtha",
        StringKey.NAKSHATRA_SHATABHISHA to "Shatabhisha",
        StringKey.NAKSHATRA_PURVA_BHADRAPADA to "Purva Bhadrapada",
        StringKey.NAKSHATRA_UTTARA_BHADRAPADA to "Uttara Bhadrapada",
        StringKey.NAKSHATRA_REVATI to "Revati",

        // Dialogs
        StringKey.DIALOG_CONFIRM_DELETE to "Confirm Delete",
        StringKey.DIALOG_DELETE_CHART_MESSAGE to "Are you sure you want to delete this chart?",
        StringKey.DIALOG_CHART_INFO to "Chart Information",
        StringKey.DIALOG_PLANET_DETAILS to "Planet Details",
        StringKey.DIALOG_HOUSE_DETAILS to "House Details",

        // Export
        StringKey.EXPORT_TITLE to "Export",
        StringKey.EXPORT_PDF to "Export as PDF",
        StringKey.EXPORT_IMAGE to "Export as Image",
        StringKey.EXPORT_TEXT to "Export as Text",
        StringKey.EXPORT_SUCCESS to "Export successful",
        StringKey.EXPORT_ERROR to "Export failed",

        // Strength Indicators
        StringKey.STRENGTH_VERY_STRONG to "Very Strong",
        StringKey.STRENGTH_STRONG to "Strong",
        StringKey.STRENGTH_MODERATE to "Moderate",
        StringKey.STRENGTH_WEAK to "Weak",
        StringKey.STRENGTH_VERY_WEAK to "Very Weak",

        // Additional Common Strings
        StringKey.CALCULATING to "Calculating...",
        StringKey.TRY_AGAIN to "Try Again",
        StringKey.GO_BACK to "Go Back",
        StringKey.NO_CHART_SELECTED to "No Chart Selected",
        StringKey.NO_CHART_SELECTED_DESC to "Please select a birth chart to view details",
        StringKey.CALCULATING_DASHA to "Calculating Dasha",
        StringKey.CALCULATING_DASHA_DESC to "Analyzing planetary periods...",
        StringKey.NO_PROFILE_SELECTED to "No Profile Selected",
        StringKey.SELECT_PROFILE_FOR_INSIGHTS to "Select a profile to view insights",
        StringKey.CURRENT_PLANETARY_PERIOD to "Current Planetary Period",
        StringKey.UPCOMING_PERIODS to "Upcoming Periods",
        StringKey.ACTIVE to "Active",
        StringKey.REMAINING to "Remaining",
        StringKey.STARTS to "Starts",
        StringKey.IN to "in",
        StringKey.PREVIEW to "Preview",
        StringKey.EXPAND to "Expand",
        StringKey.COLLAPSE to "Collapse",
        StringKey.OVERALL_ENERGY to "Overall Energy",
        StringKey.LIFE_AREAS to "Life Areas",
        StringKey.LUCKY_ELEMENTS to "Lucky Elements",
        StringKey.LUCKY_NUMBER to "Lucky Number",
        StringKey.LUCKY_COLOR to "Lucky Color",
        StringKey.LUCKY_DIRECTION to "Lucky Direction",
        StringKey.LUCKY_GEMSTONE to "Lucky Gemstone",
        StringKey.RECOMMENDATIONS to "Recommendations",
        StringKey.CAUTIONS to "Cautions",
        StringKey.TODAYS_AFFIRMATION to "Today's Affirmation",
        StringKey.WEEKLY_ENERGY_FLOW to "Weekly Energy Flow",
        StringKey.KEY_DATES to "Key Dates",
        StringKey.WEEKLY_OVERVIEW_BY_AREA to "Weekly Overview by Area",
        StringKey.WEEKLY_ADVICE to "Weekly Advice",
        StringKey.CURRENT_TRANSITS to "Current Transits",
        StringKey.INSIGHTS_UNAVAILABLE to "Insights Unavailable",
        StringKey.CALCULATIONS_NOT_COMPLETED to "Calculations could not be completed",
        StringKey.HOROSCOPE_UNAVAILABLE to "Horoscope Unavailable",
        StringKey.UNABLE_TO_CALCULATE_PLANETARY to "Unable to calculate planetary influences",
        StringKey.UNABLE_TO_LOAD_INSIGHTS to "Unable to load insights",
        StringKey.UNAVAILABLE to "Unavailable",
        StringKey.LAST_ANTARDASHA_MESSAGE to "This is the last Antardasha of the current Mahadasha",
    )

    private val nepaliStrings: Map<StringKey, String> = mapOf(
        // Common / General
        StringKey.APP_NAME to "एस्ट्रोस्टर्म",
        StringKey.OK to "ठीक छ",
        StringKey.CANCEL to "रद्द गर्नुहोस्",
        StringKey.SAVE to "सुरक्षित गर्नुहोस्",
        StringKey.DELETE to "मेटाउनुहोस्",
        StringKey.EDIT to "सम्पादन",
        StringKey.BACK to "पछाडि",
        StringKey.NEXT to "अर्को",
        StringKey.CLOSE to "बन्द गर्नुहोस्",
        StringKey.RETRY to "पुन: प्रयास",
        StringKey.LOADING to "लोड हुँदैछ...",
        StringKey.ERROR to "त्रुटि",
        StringKey.SUCCESS to "सफल",
        StringKey.WARNING to "चेतावनी",
        StringKey.INFO to "जानकारी",
        StringKey.YES to "हो",
        StringKey.NO to "होइन",
        StringKey.CONFIRM to "पुष्टि गर्नुहोस्",
        StringKey.SELECT to "छान्नुहोस्",
        StringKey.SEARCH to "खोज्नुहोस्",
        StringKey.SHARE to "साझा गर्नुहोस्",
        StringKey.COPY to "कपि गर्नुहोस्",
        StringKey.COPIED to "कपि भयो",
        StringKey.UNKNOWN to "अज्ञात",
        StringKey.NOT_AVAILABLE to "उपलब्ध छैन",

        // Error Messages
        StringKey.ERROR_GENERIC to "केही गलत भयो। कृपया पुन: प्रयास गर्नुहोस्।",
        StringKey.ERROR_NETWORK to "नेटवर्क त्रुटि। कृपया आफ्नो जडान जाँच गर्नुहोस्।",
        StringKey.ERROR_INVALID_INPUT to "अमान्य इनपुट। कृपया आफ्ना प्रविष्टिहरू जाँच गर्नुहोस्।",
        StringKey.ERROR_CALCULATION_FAILED to "गणना असफल भयो। कृपया पुन: प्रयास गर्नुहोस्।",
        StringKey.ERROR_NO_DATA to "कुनै डाटा उपलब्ध छैन।",
        StringKey.ERROR_PERMISSION_DENIED to "अनुमति अस्वीकृत।",

        // Navigation / Tabs
        StringKey.TAB_HOME to "गृह",
        StringKey.TAB_INSIGHTS to "अन्तर्दृष्टि",
        StringKey.TAB_SETTINGS to "सेटिङहरू",
        StringKey.NAV_BIRTH_CHART to "जन्म कुण्डली",
        StringKey.NAV_DASHAS to "दशा",
        StringKey.NAV_YOGAS to "योग",
        StringKey.NAV_PLANETS to "ग्रह",
        StringKey.NAV_TRANSITS to "गोचर",
        StringKey.NAV_MATCHMAKING to "कुण्डली मिलान",
        StringKey.NAV_PANCHANGA to "पञ्चाङ्ग",
        StringKey.NAV_MUHURTA to "मुहूर्त",
        StringKey.NAV_PRASHNA to "प्रश्न",
        StringKey.NAV_REMEDIES to "उपाय",
        StringKey.NAV_ASHTAKAVARGA to "अष्टकवर्ग",
        StringKey.NAV_VARSHAPHALA to "वर्षफल",

        // Settings Screen
        StringKey.SETTINGS_TITLE to "सेटिङहरू",
        StringKey.SETTINGS_LANGUAGE to "भाषा",
        StringKey.SETTINGS_LANGUAGE_DESC to "आफ्नो मनपर्ने भाषा छान्नुहोस्",
        StringKey.SETTINGS_DATE_FORMAT to "मिति ढाँचा",
        StringKey.SETTINGS_DATE_FORMAT_DESC to "मिति प्रदर्शन ढाँचा छान्नुहोस्",
        StringKey.SETTINGS_DATE_SYSTEM to "मिति प्रणाली",
        StringKey.SETTINGS_DATE_SYSTEM_AD to "ई.सं. (ग्रेगोरियन)",
        StringKey.SETTINGS_DATE_SYSTEM_BS to "वि.सं. (विक्रम सम्वत)",
        StringKey.SETTINGS_THEME to "थीम",
        StringKey.SETTINGS_THEME_DESC to "एप देखावट छान्नुहोस्",
        StringKey.SETTINGS_THEME_DARK to "गाढा",
        StringKey.SETTINGS_THEME_LIGHT to "उज्यालो",
        StringKey.SETTINGS_THEME_SYSTEM to "प्रणाली",
        StringKey.SETTINGS_ABOUT to "बारेमा",
        StringKey.SETTINGS_VERSION to "संस्करण",
        StringKey.SETTINGS_AYANAMSA to "अयनांश",
        StringKey.SETTINGS_AYANAMSA_DESC to "खगोलीय सुधार छान्नुहोस्",
        StringKey.SETTINGS_HOUSE_SYSTEM to "भाव प्रणाली",
        StringKey.SETTINGS_HOUSE_SYSTEM_DESC to "भाव गणना विधि छान्नुहोस्",

        // Chart Input Screen
        StringKey.CHART_INPUT_TITLE to "जन्म कुण्डली",
        StringKey.CHART_INPUT_NEW to "नयाँ जन्म कुण्डली",
        StringKey.CHART_INPUT_IDENTITY to "पहिचान",
        StringKey.CHART_INPUT_NAME to "पूरा नाम",
        StringKey.CHART_INPUT_NAME_PLACEHOLDER to "पूरा नाम लेख्नुहोस्",
        StringKey.CHART_INPUT_GENDER to "लिङ्ग",
        StringKey.CHART_INPUT_GENDER_MALE to "पुरुष",
        StringKey.CHART_INPUT_GENDER_FEMALE to "महिला",
        StringKey.CHART_INPUT_GENDER_OTHER to "अन्य",
        StringKey.CHART_INPUT_LOCATION to "स्थान",
        StringKey.CHART_INPUT_LOCATION_PLACEHOLDER to "शहर खोज्नुहोस् वा म्यानुअली लेख्नुहोस्",
        StringKey.CHART_INPUT_DATE_TIME to "मिति र समय",
        StringKey.CHART_INPUT_DATE to "मिति",
        StringKey.CHART_INPUT_TIME to "समय",
        StringKey.CHART_INPUT_SELECT_DATE to "मिति छान्नुहोस्",
        StringKey.CHART_INPUT_SELECT_TIME to "समय छान्नुहोस्",
        StringKey.CHART_INPUT_TIMEZONE to "समय क्षेत्र",
        StringKey.CHART_INPUT_COORDINATES to "निर्देशांक",
        StringKey.CHART_INPUT_LATITUDE to "अक्षांश",
        StringKey.CHART_INPUT_LONGITUDE to "देशान्तर",
        StringKey.CHART_INPUT_ALTITUDE to "उचाइ",
        StringKey.CHART_INPUT_ALTITUDE_OPTIONAL to "उचाइ (मिटर) - वैकल्पिक",
        StringKey.CHART_INPUT_GENERATE to "बनाउनुहोस्",
        StringKey.CHART_INPUT_GENERATE_SAVE to "बनाउनुहोस् र सुरक्षित गर्नुहोस्",
        StringKey.CHART_INPUT_ERROR_TITLE to "इनपुट त्रुटि",
        StringKey.CHART_INPUT_ERROR_LATITUDE_LONGITUDE to "कृपया वैध अक्षांश र देशान्तर लेख्नुहोस्",
        StringKey.CHART_INPUT_ERROR_LATITUDE_RANGE to "अक्षांश -९० र ९० बीचमा हुनुपर्छ",
        StringKey.CHART_INPUT_ERROR_LONGITUDE_RANGE to "देशान्तर -१८० र १८० बीचमा हुनुपर्छ",
        StringKey.CHART_INPUT_GO_BACK to "पछाडि जानुहोस्",

        // Profile Edit Screen
        StringKey.PROFILE_EDIT_TITLE to "प्रोफाइल सम्पादन",
        StringKey.PROFILE_EDIT_NO_DATA to "कुनै कुण्डली डाटा उपलब्ध छैन। कृपया सम्पादन गर्न प्रोफाइल छान्नुहोस्।",
        StringKey.PROFILE_EDIT_SAVE_SUCCESS to "प्रोफाइल सफलतापूर्वक सुरक्षित भयो",
        StringKey.PROFILE_EDIT_SAVE_ERROR to "कृपया आफ्नो इनपुट मानहरू जाँच गर्नुहोस्",

        // Birth Chart Screen
        StringKey.BIRTH_CHART_TITLE to "जन्म कुण्डली",
        StringKey.BIRTH_CHART_RASHI to "राशि",
        StringKey.BIRTH_CHART_NAVAMSA to "नवांश",
        StringKey.BIRTH_CHART_CHALIT to "चलित",
        StringKey.BIRTH_CHART_DIVISIONAL to "वर्ग कुण्डली",
        StringKey.BIRTH_CHART_ASCENDANT to "लग्न",
        StringKey.BIRTH_CHART_MOON_SIGN to "चन्द्र राशि",
        StringKey.BIRTH_CHART_SUN_SIGN to "सूर्य राशि",
        StringKey.BIRTH_CHART_NAKSHATRA to "नक्षत्र",
        StringKey.BIRTH_CHART_PADA to "पद",
        StringKey.BIRTH_CHART_DEGREE to "डिग्री",

        // Planets Screen
        StringKey.PLANETS_TITLE to "ग्रह",
        StringKey.PLANETS_POSITION to "स्थिति",
        StringKey.PLANETS_HOUSE to "भाव",
        StringKey.PLANETS_SIGN to "राशि",
        StringKey.PLANETS_DEGREE to "डिग्री",
        StringKey.PLANETS_NAKSHATRA to "नक्षत्र",
        StringKey.PLANETS_PADA to "पद",
        StringKey.PLANETS_RETROGRADE to "वक्री",
        StringKey.PLANETS_COMBUSTION to "अस्त",
        StringKey.PLANETS_EXALTED to "उच्च",
        StringKey.PLANETS_DEBILITATED to "नीच",
        StringKey.PLANETS_OWN_SIGN to "स्वगृह",
        StringKey.PLANETS_FRIENDLY to "मित्र",
        StringKey.PLANETS_NEUTRAL to "सम",
        StringKey.PLANETS_ENEMY to "शत्रु",
        StringKey.PLANETS_DIGNITY to "गौरव",

        // Planet Names
        StringKey.PLANET_SUN to "सूर्य",
        StringKey.PLANET_MOON to "चन्द्र",
        StringKey.PLANET_MARS to "मंगल",
        StringKey.PLANET_MERCURY to "बुध",
        StringKey.PLANET_JUPITER to "बृहस्पति",
        StringKey.PLANET_VENUS to "शुक्र",
        StringKey.PLANET_SATURN to "शनि",
        StringKey.PLANET_RAHU to "राहु",
        StringKey.PLANET_KETU to "केतु",
        StringKey.PLANET_ASCENDANT to "लग्न",

        // Zodiac Signs
        StringKey.SIGN_ARIES to "मेष",
        StringKey.SIGN_TAURUS to "वृष",
        StringKey.SIGN_GEMINI to "मिथुन",
        StringKey.SIGN_CANCER to "कर्कट",
        StringKey.SIGN_LEO to "सिंह",
        StringKey.SIGN_VIRGO to "कन्या",
        StringKey.SIGN_LIBRA to "तुला",
        StringKey.SIGN_SCORPIO to "वृश्चिक",
        StringKey.SIGN_SAGITTARIUS to "धनु",
        StringKey.SIGN_CAPRICORN to "मकर",
        StringKey.SIGN_AQUARIUS to "कुम्भ",
        StringKey.SIGN_PISCES to "मीन",

        // Dashas Screen
        StringKey.DASHAS_TITLE to "दशा",
        StringKey.DASHAS_MAHADASHA to "महादशा",
        StringKey.DASHAS_ANTARDASHA to "अन्तर्दशा",
        StringKey.DASHAS_PRATYANTARDASHA to "प्रत्यन्तर्दशा",
        StringKey.DASHAS_CURRENT to "वर्तमान",
        StringKey.DASHAS_START_DATE to "शुरु मिति",
        StringKey.DASHAS_END_DATE to "अन्त्य मिति",
        StringKey.DASHAS_DURATION to "अवधि",
        StringKey.DASHAS_YEARS to "वर्ष",
        StringKey.DASHAS_MONTHS to "महिना",
        StringKey.DASHAS_DAYS to "दिन",
        StringKey.DASHAS_VIMSHOTTARI to "विंशोत्तरी",
        StringKey.DASHAS_YOGINI to "योगिनी",
        StringKey.DASHAS_CHARA to "चर",

        // Yogas Screen
        StringKey.YOGAS_TITLE to "योग",
        StringKey.YOGAS_COUNT_DETECTED to "योग पाइयो",
        StringKey.YOGAS_STRENGTH to "शक्ति",
        StringKey.YOGAS_CATEGORY to "श्रेणी",
        StringKey.YOGAS_PLANETS_INVOLVED to "सम्बन्धित ग्रह",
        StringKey.YOGAS_EFFECTS to "प्रभाव",
        StringKey.YOGAS_ACTIVATION_PERIOD to "सक्रियता अवधि",
        StringKey.YOGAS_INFO_TITLE to "वैदिक योगहरूको बारेमा",
        StringKey.YOGAS_INFO_DESC to "योग वैदिक ज्योतिषमा विशेष ग्रहीय संयोजनहरू हुन् जसले विशिष्ट जीवन परिणाम र विशेषताहरू संकेत गर्छन्।",
        StringKey.YOGAS_FILTER_ALL to "सबै",
        StringKey.YOGAS_NO_YOGAS_FOUND to "यस श्रेणीमा कुनै योग फेला परेन",

        // Yoga Categories
        StringKey.YOGA_CATEGORY_RAJA to "राजयोग",
        StringKey.YOGA_CATEGORY_RAJA_DESC to "शक्ति, अधिकार, नेतृत्व",
        StringKey.YOGA_CATEGORY_DHANA to "धनयोग",
        StringKey.YOGA_CATEGORY_DHANA_DESC to "धन र समृद्धि",
        StringKey.YOGA_CATEGORY_MAHAPURUSHA to "महापुरुष योग",
        StringKey.YOGA_CATEGORY_MAHAPURUSHA_DESC to "असाधारण व्यक्तित्व गुणहरू",
        StringKey.YOGA_CATEGORY_NABHASA to "नभस योग",
        StringKey.YOGA_CATEGORY_NABHASA_DESC to "कुण्डली ढाँचा र विन्यास",
        StringKey.YOGA_CATEGORY_CHANDRA to "चन्द्र योग",
        StringKey.YOGA_CATEGORY_CHANDRA_DESC to "चन्द्रमा-आधारित संयोजन",
        StringKey.YOGA_CATEGORY_SOLAR to "सूर्य योग",
        StringKey.YOGA_CATEGORY_SOLAR_DESC to "सूर्य-आधारित संयोजन",
        StringKey.YOGA_CATEGORY_SPECIAL to "विशेष योग",
        StringKey.YOGA_CATEGORY_SPECIAL_DESC to "अद्वितीय लाभकारी संयोजन",
        StringKey.YOGA_CATEGORY_NEGATIVE to "अशुभ योग",
        StringKey.YOGA_CATEGORY_NEGATIVE_DESC to "चुनौतीपूर्ण संयोजन",

        // Matchmaking Screen
        StringKey.MATCH_TITLE to "कुण्डली मिलान",
        StringKey.MATCH_SUBTITLE to "अष्टकूट मिलान",
        StringKey.MATCH_SELECT_PROFILES to "प्रोफाइल छान्नुहोस्",
        StringKey.MATCH_BRIDE to "दुलही",
        StringKey.MATCH_GROOM to "दुलहा",
        StringKey.MATCH_TAP_TO_SELECT to "छान्न थिच्नुहोस्",
        StringKey.MATCH_SWAP_PROFILES to "प्रोफाइल स्वाप गर्नुहोस्",
        StringKey.MATCH_CLEAR_SELECTION to "चयन हटाउनुहोस्",
        StringKey.MATCH_CREATE_CHARTS_FIRST to "कुण्डली मिलान प्रयोग गर्न पहिले जन्म कुण्डली बनाउनुहोस्",
        StringKey.MATCH_CONNECTED to "जोडिएको",
        StringKey.MATCH_NOT_CONNECTED to "जोडिएको छैन",
        StringKey.MATCH_ANALYZING_COMPATIBILITY to "ब्रह्माण्डीय अनुकूलता विश्लेषण गर्दै",
        StringKey.MATCH_CALCULATING_DOSHAS to "अष्टकूट र दोष गणना गर्दै...",
        StringKey.MATCH_CALCULATION_ERROR to "गणना त्रुटि",
        StringKey.MATCH_COPIED_TO_CLIPBOARD to "रिपोर्ट क्लिपबोर्डमा कपि भयो",

        // Compatibility Score
        StringKey.MATCH_COMPATIBILITY_SCORE to "अनुकूलता स्कोर",
        StringKey.MATCH_TOTAL_SCORE to "कुल स्कोर",
        StringKey.MATCH_OUT_OF to "मध्ये",
        StringKey.MATCH_PERCENTAGE to "अनुकूलता",
        StringKey.MATCH_COMPATIBILITY to "अनुकूलता",
        StringKey.MATCH_EXCELLENT to "उत्कृष्ट",
        StringKey.MATCH_GOOD to "राम्रो",
        StringKey.MATCH_AVERAGE to "औसत",
        StringKey.MATCH_BELOW_AVERAGE to "औसतमुनि",
        StringKey.MATCH_POOR to "कमजोर",

        // Tabs
        StringKey.MATCH_TAB_OVERVIEW to "समीक्षा",
        StringKey.MATCH_TAB_GUNAS to "गुण",
        StringKey.MATCH_TAB_DOSHAS to "दोष",
        StringKey.MATCH_TAB_NAKSHATRAS to "नक्षत्र",
        StringKey.MATCH_TAB_REMEDIES to "उपाय",

        // Overview
        StringKey.MATCH_GUNA_DISTRIBUTION to "गुण स्कोर वितरण",
        StringKey.MATCH_PROFILE_COMPARISON to "प्रोफाइल तुलना",
        StringKey.MATCH_KEY_CONSIDERATIONS to "मुख्य विचारहरू",
        StringKey.MATCH_VS to "बिरुद्ध",
        StringKey.MATCH_MOON_SIGN to "चन्द्र राशि",
        StringKey.MATCH_NAKSHATRA to "नक्षत्र",
        StringKey.MATCH_PADA to "पद",
        StringKey.MATCH_FAVORABLE to "अनुकूल",
        StringKey.MATCH_NEEDS_ATTENTION to "ध्यान चाहिन्छ",

        // Gunas
        StringKey.MATCH_GUNA_VARNA to "वर्ण",
        StringKey.MATCH_GUNA_VASHYA to "वश्य",
        StringKey.MATCH_GUNA_TARA to "तारा",
        StringKey.MATCH_GUNA_YONI to "योनि",
        StringKey.MATCH_GUNA_GRAHA_MAITRI to "ग्रह मैत्री",
        StringKey.MATCH_GUNA_GANA to "गण",
        StringKey.MATCH_GUNA_BHAKOOT to "भकूट",
        StringKey.MATCH_GUNA_NADI to "नाडी",

        // Doshas
        StringKey.MATCH_MANGLIK to "मंगलिक",
        StringKey.MATCH_MANGLIK_DOSHA_ANALYSIS to "मंगलिक दोष विश्लेषण",
        StringKey.MATCH_MARS_PLACEMENT to "मंगल स्थान अनुकूलता",
        StringKey.MATCH_MARS_IN_HOUSE to "भावमा मंगल",
        StringKey.MATCH_CONTRIBUTING_FACTORS to "योगदान गर्ने कारकहरू",
        StringKey.MATCH_CANCELLATION_FACTORS to "रद्द गर्ने कारकहरू",
        StringKey.MATCH_NADI to "नाडी",
        StringKey.MATCH_NADI_DOSHA to "नाडी दोष",
        StringKey.MATCH_HEALTH_PROGENY to "स्वास्थ्य र सन्तान अनुकूलता",
        StringKey.MATCH_NADI_WARNING to "समान नाडीले सम्भावित स्वास्थ्य अनुकूलता चिन्ताहरू संकेत गर्दछ। नक्षत्र स्थितिहरूमा आधारित अपवादहरू लागू हुन सक्छन्।",
        StringKey.MATCH_BHAKOOT to "भकूट",
        StringKey.MATCH_BHAKOOT_DOSHA to "भकूट दोष",
        StringKey.MATCH_FINANCIAL_HARMONY to "आर्थिक र पारिवारिक सामञ्जस्य",
        StringKey.MATCH_BRIDE_RASHI to "दुलहीको राशि",
        StringKey.MATCH_GROOM_RASHI to "दुलहाको राशि",
        StringKey.MATCH_DOSHA_PRESENT to "दोष उपस्थित",
        StringKey.MATCH_PRESENT to "उपस्थित",
        StringKey.MATCH_ABSENT to "अनुपस्थित",
        StringKey.MATCH_NONE to "कुनै पनि छैन",

        // Nakshatra Section
        StringKey.MATCH_NAKSHATRA_COMPATIBILITY to "नक्षत्र अनुकूलता",
        StringKey.MATCH_BIRTH_STAR to "जन्म नक्षत्र विश्लेषण",
        StringKey.MATCH_BIRTH_NAKSHATRA to "जन्म नक्षत्र",
        StringKey.MATCH_NAKSHATRA_LORD to "नक्षत्र स्वामी",
        StringKey.MATCH_GANA to "गण (स्वभाव)",
        StringKey.MATCH_YONI to "योनि (पशु)",
        StringKey.MATCH_RAJJU_MATCHING to "रज्जु मिलान",
        StringKey.MATCH_LONGEVITY to "दीर्घायु र कल्याण",
        StringKey.MATCH_CONFLICT to "द्वन्द्व",
        StringKey.MATCH_COMPATIBLE to "अनुकूल",
        StringKey.MATCH_RAJJU_DESCRIPTION to "रज्जुले ब्रह्माण्डीय बन्धनलाई संकेत गर्दछ जसले जीवनसाथीको दीर्घायु र सामञ्जस्यपूर्ण वैवाहिक जीवन सुनिश्चित गर्दछ। कुनै द्वन्द्व नहुनु अत्यन्त शुभ हो।",
        StringKey.MATCH_VEDHA_ANALYSIS to "वेध विश्लेषण",
        StringKey.MATCH_OBSTRUCTION_CHECK to "अवरोध जाँच",
        StringKey.MATCH_VEDHA_DESCRIPTION to "वेधले नक्षत्र जोडाहरूलाई प्रतिनिधित्व गर्दछ जसले संयुक्त हुँदा बाधाहरू सिर्जना गर्दछ। वेधको अनुपस्थिति वैवाहिक सामञ्जस्यको लागि शुभ मानिन्छ।",
        StringKey.MATCH_STREE_DEERGHA to "स्त्री दीर्घ र महेन्द्र",
        StringKey.MATCH_PROSPERITY_FACTORS to "समृद्धि र दीर्घायु कारकहरू",
        StringKey.MATCH_STREE_DEERGHA_LABEL to "स्त्री दीर्घ",
        StringKey.MATCH_MAHENDRA to "महेन्द्र",
        StringKey.MATCH_BENEFICIAL to "लाभकारी",

        // Remedies
        StringKey.MATCH_REMEDIES to "उपाय",
        StringKey.MATCH_SUGGESTED_REMEDIES to "सुझाव गरिएका उपायहरू",
        StringKey.MATCH_VEDIC_RECOMMENDATIONS to "परम्परागत वैदिक सिफारिसहरू",
        StringKey.MATCH_REMEDIES_DISCLAIMER to "यी उपायहरू परम्परागत वैदिक ज्योतिष सिद्धान्तहरूमा आधारित छन्। व्यक्तिगत मार्गदर्शनको लागि योग्य ज्योतिषीसँग परामर्श गर्नुहोस्। अनुकूलता सफल सम्बन्धमा धेरै कारकहरू मध्ये एक हो।",

        // Share Options
        StringKey.MATCH_SHARE_REPORT to "रिपोर्ट साझा गर्नुहोस्",
        StringKey.MATCH_COPY_FULL_REPORT to "पूर्ण रिपोर्ट कपि गर्नुहोस्",
        StringKey.MATCH_COPY_FULL_DESC to "विस्तृत विश्लेषण क्लिपबोर्डमा कपि गर्नुहोस्",
        StringKey.MATCH_COPY_SUMMARY to "सारांश कपि गर्नुहोस्",
        StringKey.MATCH_COPY_SUMMARY_DESC to "संक्षिप्त अनुकूलता सारांश कपि गर्नुहोस्",
        StringKey.MATCH_COPY_SCORES to "स्कोर मात्र कपि गर्नुहोस्",
        StringKey.MATCH_COPY_SCORES_DESC to "गुण स्कोर ब्रेकडाउन कपि गर्नुहोस्",

        // Empty State
        StringKey.MATCH_NO_CHARTS to "कुनै कुण्डली उपलब्ध छैन",
        StringKey.MATCH_SELECT_BRIDE_PROFILE to "दुलहीको प्रोफाइल छान्नुहोस्",
        StringKey.MATCH_SELECT_GROOM_PROFILE to "दुलहाको प्रोफाइल छान्नुहोस्",
        StringKey.MATCH_PREPARING_ANALYSIS to "विश्लेषण तयार गर्दै...",
        StringKey.MATCH_CREATE_CHARTS to "कुण्डली मिलान प्रयोग गर्न जन्म कुण्डली बनाउनुहोस्",
        StringKey.MATCH_SELECT_TAP_CARDS to "छान्न माथिको प्रोफाइल कार्डहरूमा थिच्नुहोस्",
        StringKey.MATCH_TAP_BRIDE_CARD to "जारी राख्न दुलही कार्डमा थिच्नुहोस्",
        StringKey.MATCH_TAP_GROOM_CARD to "जारी राख्न दुलहा कार्डमा थिच्नुहोस्",
        StringKey.MATCH_CHARTS_AVAILABLE to "कुण्डली उपलब्ध",
        StringKey.MATCH_NO_CHARTS_AVAILABLE to "कुनै कुण्डली उपलब्ध छैन",
        StringKey.MATCH_SELECTED to "छानिएको",

        // Panchanga Screen
        StringKey.PANCHANGA_TITLE to "पञ्चाङ्ग",
        StringKey.PANCHANGA_TITHI to "तिथि",
        StringKey.PANCHANGA_VARA to "वार",
        StringKey.PANCHANGA_NAKSHATRA to "नक्षत्र",
        StringKey.PANCHANGA_YOGA to "योग",
        StringKey.PANCHANGA_KARANA to "करण",
        StringKey.PANCHANGA_SUNRISE to "सूर्योदय",
        StringKey.PANCHANGA_SUNSET to "सूर्यास्त",
        StringKey.PANCHANGA_MOONRISE to "चन्द्रोदय",
        StringKey.PANCHANGA_MOONSET to "चन्द्रास्त",
        StringKey.PANCHANGA_RAHUKALA to "राहु काल",
        StringKey.PANCHANGA_YAMAGANDA to "यमगण्ड",
        StringKey.PANCHANGA_GULIKAKALA to "गुलिक काल",
        StringKey.PANCHANGA_ABHIJIT_MUHURTA to "अभिजित मुहूर्त",
        StringKey.PANCHANGA_HORA to "होरा",
        StringKey.PANCHANGA_CHOGHADIYA to "चौघडिया",

        // Days of Week
        StringKey.DAY_SUNDAY to "आइतबार",
        StringKey.DAY_MONDAY to "सोमबार",
        StringKey.DAY_TUESDAY to "मंगलबार",
        StringKey.DAY_WEDNESDAY to "बुधबार",
        StringKey.DAY_THURSDAY to "बिहीबार",
        StringKey.DAY_FRIDAY to "शुक्रबार",
        StringKey.DAY_SATURDAY to "शनिबार",

        // Muhurta Screen
        StringKey.MUHURTA_TITLE to "मुहूर्त",
        StringKey.MUHURTA_AUSPICIOUS to "शुभ",
        StringKey.MUHURTA_INAUSPICIOUS to "अशुभ",
        StringKey.MUHURTA_NEUTRAL to "सामान्य",
        StringKey.MUHURTA_MARRIAGE to "विवाह",
        StringKey.MUHURTA_TRAVEL to "यात्रा",
        StringKey.MUHURTA_EDUCATION to "शिक्षा",
        StringKey.MUHURTA_BUSINESS to "व्यापार",
        StringKey.MUHURTA_CONSTRUCTION to "निर्माण",
        StringKey.MUHURTA_MEDICAL to "चिकित्सा",
        StringKey.MUHURTA_LEGAL to "कानूनी",
        StringKey.MUHURTA_RELIGIOUS to "धार्मिक",
        StringKey.MUHURTA_TODAY to "आज",
        StringKey.MUHURTA_SELECT_DATE to "मिति छान्नुहोस्",
        StringKey.MUHURTA_BEST_TIMES to "उत्तम समय",
        StringKey.MUHURTA_AVOID_TIMES to "बेला नगर्नुहोस्",

        // Prashna Screen
        StringKey.PRASHNA_TITLE to "प्रश्न",
        StringKey.PRASHNA_ASK_QUESTION to "आफ्नो प्रश्न सोध्नुहोस्",
        StringKey.PRASHNA_GENERATE_CHART to "प्रश्न कुण्डली बनाउनुहोस्",
        StringKey.PRASHNA_QUESTION_PLACEHOLDER to "यहाँ आफ्नो प्रश्न लेख्नुहोस्...",
        StringKey.PRASHNA_ANALYSIS to "विश्लेषण",
        StringKey.PRASHNA_SIGNIFIER to "कारक",
        StringKey.PRASHNA_OUTCOME to "परिणाम",
        StringKey.PRASHNA_TIMING to "समय",
        StringKey.PRASHNA_FAVORABLE to "अनुकूल",
        StringKey.PRASHNA_UNFAVORABLE to "प्रतिकूल",
        StringKey.PRASHNA_UNCERTAIN to "अनिश्चित",

        // Remedies Screen
        StringKey.REMEDIES_TITLE to "उपाय",
        StringKey.REMEDIES_GEMSTONES to "रत्न",
        StringKey.REMEDIES_MANTRAS to "मन्त्र",
        StringKey.REMEDIES_YANTRAS to "यन्त्र",
        StringKey.REMEDIES_DONATIONS to "दान",
        StringKey.REMEDIES_FASTING to "व्रत",
        StringKey.REMEDIES_RITUALS to "पूजा विधि",
        StringKey.REMEDIES_LIFESTYLE to "जीवनशैली",
        StringKey.REMEDIES_FAVORABLE_DAY to "शुभ दिन",
        StringKey.REMEDIES_METAL to "धातु",
        StringKey.REMEDIES_COLOR to "रंग",
        StringKey.REMEDIES_DIRECTION to "दिशा",
        StringKey.REMEDIES_DEITY to "देवता",
        StringKey.REMEDIES_RECOMMENDED_FOR to "सिफारिस गरिएको",
        StringKey.REMEDIES_PRECAUTIONS to "सावधानी",

        // Transits Screen
        StringKey.TRANSITS_TITLE to "गोचर",
        StringKey.TRANSITS_CURRENT to "वर्तमान",
        StringKey.TRANSITS_UPCOMING to "आगामी",
        StringKey.TRANSITS_PAST to "बितेको",
        StringKey.TRANSITS_PLANET_TRANSIT to "ग्रह गोचर",
        StringKey.TRANSITS_FROM to "बाट",
        StringKey.TRANSITS_TO to "मा",
        StringKey.TRANSITS_DURATION to "अवधि",
        StringKey.TRANSITS_EFFECTS to "प्रभाव",
        StringKey.TRANSITS_FAVORABLE to "अनुकूल",
        StringKey.TRANSITS_CHALLENGING to "चुनौतीपूर्ण",
        StringKey.TRANSITS_NEUTRAL to "सामान्य",

        // Ashtakavarga Screen
        StringKey.ASHTAKAVARGA_TITLE to "अष्टकवर्ग",
        StringKey.ASHTAKAVARGA_SARVASHTAKA to "सर्वाष्टकवर्ग",
        StringKey.ASHTAKAVARGA_POINTS to "बिन्दु",
        StringKey.ASHTAKAVARGA_TOTAL to "कुल",
        StringKey.ASHTAKAVARGA_STRONG_HOUSES to "बलवान भावहरू",
        StringKey.ASHTAKAVARGA_WEAK_HOUSES to "दुर्बल भावहरू",
        StringKey.ASHTAKAVARGA_INTERPRETATION to "व्याख्या",

        // Varshaphala Screen
        StringKey.VARSHAPHALA_TITLE to "वर्षफल",
        StringKey.VARSHAPHALA_YEAR to "वर्ष",
        StringKey.VARSHAPHALA_MUNTHA to "मुन्था",
        StringKey.VARSHAPHALA_SAHAMS to "सहम",
        StringKey.VARSHAPHALA_YEAR_LORD to "वर्षेश",
        StringKey.VARSHAPHALA_PREDICTIONS to "भविष्यवाणी",
        StringKey.VARSHAPHALA_CAREER to "पेशा",
        StringKey.VARSHAPHALA_FINANCE to "आर्थिक",
        StringKey.VARSHAPHALA_HEALTH to "स्वास्थ्य",
        StringKey.VARSHAPHALA_RELATIONSHIPS to "सम्बन्ध",

        // Home Screen
        StringKey.HOME_WELCOME to "स्वागत छ",
        StringKey.HOME_TODAYS_PANCHANGA to "आजको पञ्चाङ्ग",
        StringKey.HOME_CURRENT_DASHA to "वर्तमान दशा",
        StringKey.HOME_QUICK_ACCESS to "द्रुत पहुँच",
        StringKey.HOME_RECENT_CHARTS to "हालका कुण्डलीहरू",
        StringKey.HOME_CREATE_NEW_CHART to "नयाँ कुण्डली बनाउनुहोस्",
        StringKey.HOME_VIEW_ALL_CHARTS to "सबै कुण्डली हेर्नुहोस्",
        StringKey.HOME_NO_CHARTS to "अहिलेसम्म कुनै कुण्डली छैन",
        StringKey.HOME_CREATE_FIRST_CHART to "आफ्नो पहिलो जन्म कुण्डली बनाउनुहोस्",

        // Insights Tab
        StringKey.INSIGHTS_TITLE to "अन्तर्दृष्टि",
        StringKey.INSIGHTS_SUMMARY to "सारांश",
        StringKey.INSIGHTS_STRENGTHS to "शक्तिहरू",
        StringKey.INSIGHTS_CHALLENGES to "चुनौतीहरू",
        StringKey.INSIGHTS_OPPORTUNITIES to "अवसरहरू",
        StringKey.INSIGHTS_CAREER to "पेशा",
        StringKey.INSIGHTS_RELATIONSHIPS to "सम्बन्ध",
        StringKey.INSIGHTS_HEALTH to "स्वास्थ्य",
        StringKey.INSIGHTS_FINANCE to "आर्थिक",
        StringKey.INSIGHTS_SPIRITUALITY to "आध्यात्मिकता",
        StringKey.INSIGHTS_LIFE_PATH to "जीवन मार्ग",

        // Date Picker
        StringKey.DATE_SELECT_DATE to "मिति छान्नुहोस्",
        StringKey.DATE_SELECT_TIME to "समय छान्नुहोस्",
        StringKey.DATE_AD to "ई.सं.",
        StringKey.DATE_BS to "वि.सं.",
        StringKey.DATE_TODAY to "आज",
        StringKey.DATE_YEAR to "वर्ष",
        StringKey.DATE_MONTH to "महिना",
        StringKey.DATE_DAY to "दिन",

        // Nepali Months
        StringKey.MONTH_BAISAKH to "बैशाख",
        StringKey.MONTH_JESTHA to "जेठ",
        StringKey.MONTH_ASHADH to "असार",
        StringKey.MONTH_SHRAWAN to "साउन",
        StringKey.MONTH_BHADRA to "भदौ",
        StringKey.MONTH_ASHWIN to "असोज",
        StringKey.MONTH_KARTIK to "कात्तिक",
        StringKey.MONTH_MANGSIR to "मंसिर",
        StringKey.MONTH_POUSH to "पुष",
        StringKey.MONTH_MAGH to "माघ",
        StringKey.MONTH_FALGUN to "फागुन",
        StringKey.MONTH_CHAITRA to "चैत्र",

        // English Months
        StringKey.MONTH_JANUARY to "जनवरी",
        StringKey.MONTH_FEBRUARY to "फेब्रुअरी",
        StringKey.MONTH_MARCH to "मार्च",
        StringKey.MONTH_APRIL to "अप्रिल",
        StringKey.MONTH_MAY to "मे",
        StringKey.MONTH_JUNE to "जुन",
        StringKey.MONTH_JULY to "जुलाई",
        StringKey.MONTH_AUGUST to "अगस्ट",
        StringKey.MONTH_SEPTEMBER to "सेप्टेम्बर",
        StringKey.MONTH_OCTOBER to "अक्टोबर",
        StringKey.MONTH_NOVEMBER to "नोभेम्बर",
        StringKey.MONTH_DECEMBER to "डिसेम्बर",

        // Houses
        StringKey.HOUSE_1 to "प्रथम भाव",
        StringKey.HOUSE_2 to "द्वितीय भाव",
        StringKey.HOUSE_3 to "तृतीय भाव",
        StringKey.HOUSE_4 to "चतुर्थ भाव",
        StringKey.HOUSE_5 to "पञ्चम भाव",
        StringKey.HOUSE_6 to "षष्ठ भाव",
        StringKey.HOUSE_7 to "सप्तम भाव",
        StringKey.HOUSE_8 to "अष्टम भाव",
        StringKey.HOUSE_9 to "नवम भाव",
        StringKey.HOUSE_10 to "दशम भाव",
        StringKey.HOUSE_11 to "एकादश भाव",
        StringKey.HOUSE_12 to "द्वादश भाव",

        // House Names
        StringKey.HOUSE_1_NAME to "लग्न (आत्मा)",
        StringKey.HOUSE_2_NAME to "धन (सम्पत्ति)",
        StringKey.HOUSE_3_NAME to "सहज (भाइबहिनी)",
        StringKey.HOUSE_4_NAME to "सुख (गृह)",
        StringKey.HOUSE_5_NAME to "पुत्र (सन्तान)",
        StringKey.HOUSE_6_NAME to "रिपु (शत्रु)",
        StringKey.HOUSE_7_NAME to "कलत्र (जीवनसाथी)",
        StringKey.HOUSE_8_NAME to "आयुर (दीर्घायु)",
        StringKey.HOUSE_9_NAME to "धर्म (भाग्य)",
        StringKey.HOUSE_10_NAME to "कर्म (पेशा)",
        StringKey.HOUSE_11_NAME to "लाभ (आम्दानी)",
        StringKey.HOUSE_12_NAME to "व्यय (खर्च)",

        // Nakshatras
        StringKey.NAKSHATRA_ASHWINI to "अश्विनी",
        StringKey.NAKSHATRA_BHARANI to "भरणी",
        StringKey.NAKSHATRA_KRITTIKA to "कृत्तिका",
        StringKey.NAKSHATRA_ROHINI to "रोहिणी",
        StringKey.NAKSHATRA_MRIGASHIRA to "मृगशिरा",
        StringKey.NAKSHATRA_ARDRA to "आर्द्रा",
        StringKey.NAKSHATRA_PUNARVASU to "पुनर्वसु",
        StringKey.NAKSHATRA_PUSHYA to "पुष्य",
        StringKey.NAKSHATRA_ASHLESHA to "आश्लेषा",
        StringKey.NAKSHATRA_MAGHA to "मघा",
        StringKey.NAKSHATRA_PURVA_PHALGUNI to "पूर्वाफाल्गुनी",
        StringKey.NAKSHATRA_UTTARA_PHALGUNI to "उत्तराफाल्गुनी",
        StringKey.NAKSHATRA_HASTA to "हस्ता",
        StringKey.NAKSHATRA_CHITRA to "चित्रा",
        StringKey.NAKSHATRA_SWATI to "स्वाती",
        StringKey.NAKSHATRA_VISHAKHA to "विशाखा",
        StringKey.NAKSHATRA_ANURADHA to "अनुराधा",
        StringKey.NAKSHATRA_JYESHTHA to "ज्येष्ठा",
        StringKey.NAKSHATRA_MULA to "मूल",
        StringKey.NAKSHATRA_PURVA_ASHADHA to "पूर्वाषाढा",
        StringKey.NAKSHATRA_UTTARA_ASHADHA to "उत्तराषाढा",
        StringKey.NAKSHATRA_SHRAVANA to "श्रवण",
        StringKey.NAKSHATRA_DHANISHTHA to "धनिष्ठा",
        StringKey.NAKSHATRA_SHATABHISHA to "शतभिषा",
        StringKey.NAKSHATRA_PURVA_BHADRAPADA to "पूर्वाभाद्रपदा",
        StringKey.NAKSHATRA_UTTARA_BHADRAPADA to "उत्तराभाद्रपदा",
        StringKey.NAKSHATRA_REVATI to "रेवती",

        // Dialogs
        StringKey.DIALOG_CONFIRM_DELETE to "मेट्ने पुष्टि गर्नुहोस्",
        StringKey.DIALOG_DELETE_CHART_MESSAGE to "के तपाईं यो कुण्डली मेटाउन निश्चित हुनुहुन्छ?",
        StringKey.DIALOG_CHART_INFO to "कुण्डली जानकारी",
        StringKey.DIALOG_PLANET_DETAILS to "ग्रह विवरण",
        StringKey.DIALOG_HOUSE_DETAILS to "भाव विवरण",

        // Export
        StringKey.EXPORT_TITLE to "निर्यात",
        StringKey.EXPORT_PDF to "PDF मा निर्यात",
        StringKey.EXPORT_IMAGE to "छविमा निर्यात",
        StringKey.EXPORT_TEXT to "पाठमा निर्यात",
        StringKey.EXPORT_SUCCESS to "निर्यात सफल",
        StringKey.EXPORT_ERROR to "निर्यात असफल",

        // Strength Indicators
        StringKey.STRENGTH_VERY_STRONG to "अत्यन्त बलवान",
        StringKey.STRENGTH_STRONG to "बलवान",
        StringKey.STRENGTH_MODERATE to "मध्यम",
        StringKey.STRENGTH_WEAK to "दुर्बल",
        StringKey.STRENGTH_VERY_WEAK to "अत्यन्त दुर्बल",

        // Additional Common Strings
        StringKey.CALCULATING to "गणना गर्दै...",
        StringKey.TRY_AGAIN to "पुन: प्रयास गर्नुहोस्",
        StringKey.GO_BACK to "पछाडि जानुहोस्",
        StringKey.NO_CHART_SELECTED to "कुनै कुण्डली छानिएको छैन",
        StringKey.NO_CHART_SELECTED_DESC to "विवरण हेर्न कृपया जन्म कुण्डली छान्नुहोस्",
        StringKey.CALCULATING_DASHA to "दशा गणना गर्दै",
        StringKey.CALCULATING_DASHA_DESC to "ग्रहीय अवधि विश्लेषण गर्दै...",
        StringKey.NO_PROFILE_SELECTED to "कुनै प्रोफाइल छानिएको छैन",
        StringKey.SELECT_PROFILE_FOR_INSIGHTS to "अन्तर्दृष्टि हेर्न प्रोफाइल छान्नुहोस्",
        StringKey.CURRENT_PLANETARY_PERIOD to "वर्तमान ग्रहीय अवधि",
        StringKey.UPCOMING_PERIODS to "आगामी अवधिहरू",
        StringKey.ACTIVE to "सक्रिय",
        StringKey.REMAINING to "बाँकी",
        StringKey.STARTS to "शुरु हुन्छ",
        StringKey.IN to "मा",
        StringKey.PREVIEW to "पूर्वावलोकन",
        StringKey.EXPAND to "विस्तार",
        StringKey.COLLAPSE to "संक्षिप्त",
        StringKey.OVERALL_ENERGY to "समग्र ऊर्जा",
        StringKey.LIFE_AREAS to "जीवन क्षेत्रहरू",
        StringKey.LUCKY_ELEMENTS to "भाग्यशाली तत्वहरू",
        StringKey.LUCKY_NUMBER to "भाग्यशाली अंक",
        StringKey.LUCKY_COLOR to "भाग्यशाली रंग",
        StringKey.LUCKY_DIRECTION to "भाग्यशाली दिशा",
        StringKey.LUCKY_GEMSTONE to "भाग्यशाली रत्न",
        StringKey.RECOMMENDATIONS to "सिफारिसहरू",
        StringKey.CAUTIONS to "सावधानीहरू",
        StringKey.TODAYS_AFFIRMATION to "आजको सकारात्मक वाक्य",
        StringKey.WEEKLY_ENERGY_FLOW to "साप्ताहिक ऊर्जा प्रवाह",
        StringKey.KEY_DATES to "महत्त्वपूर्ण मितिहरू",
        StringKey.WEEKLY_OVERVIEW_BY_AREA to "क्षेत्रअनुसार साप्ताहिक समीक्षा",
        StringKey.WEEKLY_ADVICE to "साप्ताहिक सल्लाह",
        StringKey.CURRENT_TRANSITS to "वर्तमान गोचर",
        StringKey.INSIGHTS_UNAVAILABLE to "अन्तर्दृष्टि उपलब्ध छैन",
        StringKey.CALCULATIONS_NOT_COMPLETED to "गणना पूरा हुन सकेन",
        StringKey.HOROSCOPE_UNAVAILABLE to "राशिफल उपलब्ध छैन",
        StringKey.UNABLE_TO_CALCULATE_PLANETARY to "ग्रहीय प्रभाव गणना गर्न असमर्थ",
        StringKey.UNABLE_TO_LOAD_INSIGHTS to "अन्तर्दृष्टि लोड गर्न असमर्थ",
        StringKey.UNAVAILABLE to "उपलब्ध छैन",
        StringKey.LAST_ANTARDASHA_MESSAGE to "यो वर्तमान महादशाको अन्तिम अन्तर्दशा हो",
    )

    /**
     * Get string for the given key in the specified language
     */
    fun getString(key: StringKey, language: Language): String {
        return when (language) {
            Language.ENGLISH -> englishStrings[key] ?: key.name
            Language.NEPALI -> nepaliStrings[key] ?: englishStrings[key] ?: key.name
        }
    }

    /**
     * Get all strings for a specific language
     */
    fun getAllStrings(language: Language): Map<StringKey, String> {
        return when (language) {
            Language.ENGLISH -> englishStrings
            Language.NEPALI -> nepaliStrings
        }
    }
}
